"""initial schema

Revision ID: 786b9fcdb24d
Revises: 
Create Date: 2026-04-14 13:15:30.560676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '786b9fcdb24d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('chains', postgresql.ARRAY(sa.String(length=100)), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('official_domain', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_protocol_name')
    )
    op.create_table('watched_proxies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proxy_address', sa.String(length=42), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('proxy_type', sa.String(), nullable=True),
    sa.Column('last_known_implementation', sa.String(length=42), nullable=True),
    sa.Column('last_scanned_block', sa.Integer(), nullable=False),
    sa.Column('needs_polling', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proxy_address', 'chain', name='uq_watched_proxy_address_chain')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('stage', sa.Enum('discovery', 'dapp_crawl', 'defillama_scan', 'static', 'resolution', 'policy', 'done', name='jobstage'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_stage_status', 'jobs', ['stage', 'status'], unique=False)
    op.create_table('protocol_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('discord_webhook_url', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('event_filter', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_protocol_subscriptions_protocol_id', 'protocol_subscriptions', ['protocol_id'], unique=False)
    op.create_table('proxy_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watched_proxy_id', sa.UUID(), nullable=False),
    sa.Column('discord_webhook_url', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watched_proxy_id'], ['watched_proxies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy_upgrade_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watched_proxy_id', sa.UUID(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('old_implementation', sa.String(length=42), nullable=True),
    sa.Column('new_implementation', sa.String(length=42), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watched_proxy_id'], ['watched_proxies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tvl_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('defillama_tvl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('chain_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('contract_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tvl_snapshots_protocol_timestamp', 'tvl_snapshots', ['protocol_id', 'timestamp'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('text_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'name', name='uq_artifact_job_name')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('source_verified', sa.Boolean(), nullable=True),
    sa.Column('chain', sa.String(length=100), nullable=True),
    sa.Column('contract_name', sa.String(length=255), nullable=True),
    sa.Column('compiler_version', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('evm_version', sa.String(length=50), nullable=True),
    sa.Column('optimization', sa.Boolean(), nullable=True),
    sa.Column('optimization_runs', sa.Integer(), nullable=True),
    sa.Column('source_format', sa.String(length=50), nullable=True),
    sa.Column('source_file_count', sa.Integer(), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('is_proxy', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('proxy_type', sa.String(length=50), nullable=True),
    sa.Column('implementation', sa.String(length=42), nullable=True),
    sa.Column('beacon', sa.String(length=42), nullable=True),
    sa.Column('admin', sa.String(length=42), nullable=True),
    sa.Column('deployer', sa.String(length=42), nullable=True),
    sa.Column('remappings', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('rank_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('discovery_source', sa.String(length=100), nullable=True),
    sa.Column('discovery_url', sa.Text(), nullable=True),
    sa.Column('chains', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', 'chain', name='uq_contract_address_chain')
    )
    op.create_index('ix_contracts_job_id', 'contracts', ['job_id'], unique=False)
    op.create_index('ix_contracts_protocol_id', 'contracts', ['protocol_id'], unique=False)
    op.create_table('dapp_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('to_address', sa.String(length=42), nullable=True),
    sa.Column('value', sa.String(length=80), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('method_selector', sa.String(length=10), nullable=True),
    sa.Column('typed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_permit', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dapp_interactions_job_id', 'dapp_interactions', ['job_id'], unique=False)
    op.create_index('ix_dapp_interactions_protocol_id', 'dapp_interactions', ['protocol_id'], unique=False)
    op.create_index('ix_dapp_interactions_to_address', 'dapp_interactions', ['to_address'], unique=False)
    op.create_table('source_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('token_address', sa.String(length=42), nullable=True),
    sa.Column('token_name', sa.String(length=255), nullable=True),
    sa.Column('token_symbol', sa.String(length=50), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('raw_balance', sa.String(), nullable=False),
    sa.Column('usd_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_balances_contract_id', 'contract_balances', ['contract_id'], unique=False)
    op.create_table('contract_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('dependency_address', sa.String(length=42), nullable=False),
    sa.Column('dependency_name', sa.String(length=255), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('source', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('proxy_type', sa.String(length=50), nullable=True),
    sa.Column('implementation', sa.String(length=42), nullable=True),
    sa.Column('admin', sa.String(length=42), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('control_model', sa.String(length=50), nullable=True),
    sa.Column('is_upgradeable', sa.Boolean(), nullable=True),
    sa.Column('is_pausable', sa.Boolean(), nullable=True),
    sa.Column('has_timelock', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('is_factory', sa.Boolean(), nullable=True),
    sa.Column('is_nft', sa.Boolean(), nullable=True),
    sa.Column('standards', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('source_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    op.create_table('control_graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.String(length=255), nullable=False),
    sa.Column('to_node_id', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('source_controller_id', sa.String(length=255), nullable=True),
    sa.Column('notes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_graph_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=True),
    sa.Column('resolved_type', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('contract_name', sa.String(length=255), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controller_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('controller_id', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=66), nullable=True),
    sa.Column('resolved_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_via', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('effective_functions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('selector', sa.String(length=10), nullable=True),
    sa.Column('abi_signature', sa.Text(), nullable=True),
    sa.Column('effect_labels', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('effect_targets', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('action_summary', sa.Text(), nullable=True),
    sa.Column('authority_public', sa.Boolean(), nullable=False),
    sa.Column('authority_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitored_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('chain', sa.String(length=100), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('watched_proxy_id', sa.UUID(), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('monitoring_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_known_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_scanned_block', sa.Integer(), nullable=False),
    sa.Column('needs_polling', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enrollment_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['watched_proxy_id'], ['watched_proxies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', 'chain', name='uq_monitored_contract_address_chain')
    )
    op.create_index('ix_monitored_contracts_protocol_id', 'monitored_contracts', ['protocol_id'], unique=False)
    op.create_table('principal_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('resolved_type', sa.String(length=50), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('graph_context', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privileged_functions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('selector', sa.String(length=10), nullable=True),
    sa.Column('abi_signature', sa.Text(), nullable=True),
    sa.Column('effect_labels', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('action_summary', sa.Text(), nullable=True),
    sa.Column('authority_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('declared_in', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upgrade_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('proxy_address', sa.String(length=42), nullable=False),
    sa.Column('old_impl', sa.String(length=42), nullable=True),
    sa.Column('new_impl', sa.String(length=42), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function_principals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('resolved_type', sa.String(length=50), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('principal_type', sa.String(length=50), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['effective_functions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitored_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitored_contract_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitored_contract_id'], ['monitored_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_monitored_events_contract_id', 'monitored_events', ['monitored_contract_id'], unique=False)
    op.create_index('ix_monitored_events_detected_at', 'monitored_events', ['detected_at'], unique=False)
    op.create_index('ix_monitored_events_event_type', 'monitored_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monitored_events_event_type', table_name='monitored_events')
    op.drop_index('ix_monitored_events_detected_at', table_name='monitored_events')
    op.drop_index('ix_monitored_events_contract_id', table_name='monitored_events')
    op.drop_table('monitored_events')
    op.drop_table('function_principals')
    op.drop_table('upgrade_events')
    op.drop_table('role_definitions')
    op.drop_table('privileged_functions')
    op.drop_table('principal_labels')
    op.drop_index('ix_monitored_contracts_protocol_id', table_name='monitored_contracts')
    op.drop_table('monitored_contracts')
    op.drop_table('effective_functions')
    op.drop_table('controller_values')
    op.drop_table('control_graph_nodes')
    op.drop_table('control_graph_edges')
    op.drop_table('contract_summaries')
    op.drop_table('contract_dependencies')
    op.drop_index('ix_contract_balances_contract_id', table_name='contract_balances')
    op.drop_table('contract_balances')
    op.drop_table('source_files')
    op.drop_index('ix_dapp_interactions_to_address', table_name='dapp_interactions')
    op.drop_index('ix_dapp_interactions_protocol_id', table_name='dapp_interactions')
    op.drop_index('ix_dapp_interactions_job_id', table_name='dapp_interactions')
    op.drop_table('dapp_interactions')
    op.drop_index('ix_contracts_protocol_id', table_name='contracts')
    op.drop_index('ix_contracts_job_id', table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('artifacts')
    op.drop_index('ix_tvl_snapshots_protocol_timestamp', table_name='tvl_snapshots')
    op.drop_table('tvl_snapshots')
    op.drop_table('proxy_upgrade_events')
    op.drop_table('proxy_subscriptions')
    op.drop_index('ix_protocol_subscriptions_protocol_id', table_name='protocol_subscriptions')
    op.drop_table('protocol_subscriptions')
    op.drop_index('ix_jobs_stage_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('watched_proxies')
    op.drop_table('protocols')
    # ### end Alembic commands ###
