[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.21"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
remappings = ["@openzeppelin/=src/lib/openzeppelin-contracts/", "@solmate/=src/lib/solmate/src/"]

