"""add canonical_slug to protocols

Revision ID: 95ccb994b48c
Revises: 850ff90146d7
Create Date: 2026-04-28 15:41:04.251479

Safety checklist (delete once reviewed):
  - CREATE INDEX CONCURRENTLY / ALTER TYPE ADD VALUE must run in
    ``with op.get_context().autocommit_block():`` — they cannot run inside
    a transaction.
  - Adding a NOT NULL column to a populated table needs a server_default
    (or a 3-step add-nullable / backfill / set-not-null sequence).
  - Don't rename columns in one step on a live deploy — old code is still
    reading the old name. Add new column, dual-write, drop later.
  - env.py sets lock_timeout=10s / statement_timeout=300s. Override inside
    the migration if the operation legitimately needs longer.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "95ccb994b48c"
down_revision: Union[str, Sequence[str], None] = "850ff90146d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("protocols", sa.Column("canonical_slug", sa.String(length=255), nullable=True))
    op.create_unique_constraint("uq_protocol_canonical_slug", "protocols", ["canonical_slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_protocol_canonical_slug", "protocols", type_="unique")
    op.drop_column("protocols", "canonical_slug")
    # ### end Alembic commands ###
